NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /api/v1
    type:     rest