# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    scrapyd-server: "%scrapy-server%"

services:
    scrapy_helper:
        class: AppBundle\Helper\ScrapydHelper
        arguments: ["%scrapyd-server%"]
